services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clientesdb
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservice-network


  eureka:
    image: eureka:latest
    container_name: eureka
    build:
      context: ./eureka
    ports:
      - "8761:8761"
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  cliente-service:
    image: cliente-service:latest
    container_name: cliente-service
    build:
      context: ./cliente-service
    ports:
      - "8080:8080"
    networks:
      - microservice-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/clientesdb
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://eureka:8761/eureka
    depends_on:
      - eureka
      - mysql

networks:
  microservice-network:
    driver: bridge

volumes:
  mysql-data: